# Generated by Django 3.0.3 on 2020-02-21 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.CharField(max_length=100)),
                ('logging_date', models.DateTimeField(auto_now_add=True)),
                ('logging_mode', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('ERROR', 'Error'), ('WARN', 'Warning')], default='INFO', max_length=10)),
            ],
        ),
    ]
