# Generated by Django 3.0.3 on 2020-02-21 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyLogs', '0002_auto_20200221_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='mylogs',
            name='logged_data',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
